name: Build and test

on:
  push:
    branches:
    - 'pandas-on-spark-tests'

jobs:
  pyspark:
    name: "Build modules: Python ${{ matrix.python-version }}, pandas ${{ matrix.pandas-version }}"
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: 3.6
            pandas-version: 1.0.5
          - python-version: 3.6
            pandas-version: 1.1.5
          - python-version: 3.9
            pandas-version: 1.1.5
          - python-version: 3.9
            pandas-version: 1.2.0
    env:
      HADOOP_PROFILE: hadoop3.2
      HIVE_PROFILE: hive2.3
      GITHUB_PREV_SHA: ${{ github.event.before }}
      SPARK_LOCAL_IP: localhost
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cache Scala, SBT and Maven
      uses: actions/cache@v2
      with:
        path: |
          build/apache-maven-*
          build/scala-*
          build/*.jar
          ~/.sbt
        key: build-${{ hashFiles('**/pom.xml', 'project/build.properties', 'build/mvn', 'build/sbt', 'build/sbt-launch-lib.bash', 'build/spark-build-info') }}
        restore-keys: |
          build-
    - name: Cache Coursier local repository
      uses: actions/cache@v2
      with:
        path: ~/.cache/coursier
        key: pyspark-coursier-${{ hashFiles('**/pom.xml', '**/plugins.sbt') }}
        restore-keys: |
          pyspark-coursier-
    - name: Install Java 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: Install Python packages
      run: |
        python${{ matrix.python-version }} -m pip install numpy 'pyarrow<5.0.0' 'pandas==${{ matrix.pandas-version }}' scipy xmlrunner plotly>=4.8
        python${{ matrix.python-version }} -m pip list
    - name: Build Spark
      run: |
        ./build/sbt -Phive-thriftserver package
    # Run the tests.
    - name: Run tests
      run: |
        ./python/run-tests --python-executables python${{ matrix.python-version }} --parallelism 2 --modules pyspark-pandas
    - name: Upload test results to report
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results-${{ matrix.modules }}--8-hadoop3.2-hive2.3
        path: "**/target/test-reports/*.xml"
    - name: Upload unit tests log files
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: unit-tests-log-${{ matrix.modules }}--8-hadoop3.2-hive2.3
        path: "**/target/unit-tests.log"
